name: ${name}
version: ${version}
api-version: 1.13
authors: [shikendon, WhiteCat]

main: github.phateio.rangedchat.RangedChat

commands:
  rc:
    description: RangedChat commands
    usage: /<command>
